# Generated by Django 5.2.7 on 2025-11-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Преподаватель (старое)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachersubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='teachers_app.teachersubject', verbose_name='Преподаватель + Предмет + Курс'),
        ),
    ]
