# Generated by Django 5.2.7 on 2025-11-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_alter_lesson_options_remove_lesson_teacher_and_more'),
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='teachers_app.teacher', verbose_name='Преподаватель'),
        ),
    ]
