# Generated by Django 5.2.7 on 2025-11-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место')),
                ('organizer', models.CharField(blank=True, max_length=255, verbose_name='Организатор')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящее'), ('ongoing', 'Сейчас'), ('completed', 'Прошедшее')], default='upcoming', max_length=100, verbose_name='Статус')),
                ('type_status', models.CharField(choices=[('sport', 'Спорт'), ('competition', 'Соревнование'), ('conference', 'Конференция'), ('courses', 'Курсы'), ('seminar', 'Семинар'), ('cultural', 'Культурное')], default='cultural', max_length=100, verbose_name='Тип мероприятия')),
                ('participants_limit', models.PositiveIntegerField(default=0, verbose_name='Лимит участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущие участники')),
                ('groups', models.ManyToManyField(blank=True, to='schedule_app.group', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
