# Generated by Django 5.2.7 on 2025-11-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кафедры')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('professor', 'Профессор'), ('associate_professor', 'Доцент'), ('assistant', 'Ассистент'), ('senior_lecturer', 'Старший преподаватель'), ('lecturer', 'Преподаватель')], max_length=50, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('office', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
                ('consultation_schedule', models.TextField(blank=True, help_text='Например: Пн 16:00-18:00, Чт 14:00-16:00', verbose_name='График консультаций')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_app.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, help_text='Например: ИУ7-71Б', max_length=50, verbose_name='Курс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель-Предмет',
                'verbose_name_plural': 'Преподаватели-Предметы',
            },
        ),
    ]
